config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  namespace :api do
    get 'questions' => 'questions#index'
    post 'questions/new' => 'questions#create'
    post 'answers/new' => 'answers#create'
    post 'answer/correct/:id' => 'answers#markCorrect'
    delete 'question/:id/delete' => 'questions#destroy'
  end

  resources :questions do resources :answers
  end
  resources :users

  get 'sessions/new' => 'sessions#new', as: :login
  post 'sessions/new' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy', as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  include PgSearch
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  include PgSearch
  belongs_to :user
  has_many :answers
  scope :username, -> { User.find_by(:id => Question.users_id) }
  pg_search_scope :search, against: [:title, :text], :using => {:tsearch => {:prefix => true}}
  pg_search_scope :search_by_title, against: :title, :using => {:tsearch => {:prefix => true}}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token :api_token
  has_many :questions
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.question_id = params[:question_id]
    @answer.user_id = session[:user_id]

    if @answer.save!
      # FIXME: Should go back to question tied to this new answer
      redirect_to root_path
    else
      render :new
    end
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.correct = true
    @answer.save

    redirect_to question_path(@question)
  end

  def destroy
  end

  private
  def answer_params
    params.require(:answer).permit(:id, :text)
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  # prevent the need for api token for certain actions
  protect_from_forgery with: :null_session

  def authenticate_user!
    # this requests the token be in the header
    header = request.headers["authorization"] || ""
    api_token = header.gsub("Bearer ", "")
    # this requests the token by in the URL itself as params
    # its not working... dunno why
    # if api_token.blank?
    #   api_token = params[:api_token]
    # end

    @current_user = User.find_by api_token: api_token
    if @current_user.blank?
      render json: {status: "unauthorized", message: "API Token missing or invalid"}, status: 401
    end
  end
end

app/controllers/api/questions_controller.rb
class Api::QuestionsController < Api::ApiController
  before_action :authenticate_user!, only: [:update, :create, :destroy]
  def index
    @questions = Question.all
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = @current_user.id

    if @question.save!
      head :created
    else
      render json: {message: 'Question not created.'}, status: 422
    end
  end

  def update

  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    head :ok
  end

  private
  def question_params
    params.require(:question).permit(:id, :title, :text, :users_id, :answers_id)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def index
    @questions = Question.all
    render json: @questions
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      render json: @question, status: :created, location: @question
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def question_params
    params.require(:question).permit(:title, :text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.all.page(params[:page]).per(10)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    if params[:query].present?
      @questions = Question.search(params[:query]).page(params[:page]).per(10)
    else
      @questions = Question.page(params[:page]).per(10)
    end
  end

  # @posts = Post.page(params[:page]).per(10)

  def new

  end

  def create
    @question = Question.new(question_params)
    @question.user_id = session[:user_id]

    if @question.save!
      redirect_to @question
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])

    # FIXME
    @answers = Answer.all
  end

  def update
    @question = Question.find(params[:id])
  end

  private
  def question_params
    params.require(:question).permit(:id, :title, :text, :users_id, :answers_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].present?
     @questions = Question.search(params[:query])
   else
     @questions = Question.all
   end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by username: params[:username]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @message = 'Username / Password Incorrect'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @users = User.all
    redirect_to root_path
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit

  end

  def show
    @user = User.find(params[:id])
  end

  def update

  end

  def destroy

  end

  private
  def user_params
    params.require(:user).permit(:id, :username, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/api/answers_helper.rb
module Api::AnswersHelper
end

app/helpers/api/api_helper.rb
module Api::ApiHelper
end

app/helpers/api/questions_helper.rb
module Api::QuestionsHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/questions/index.html.erb
<h1>Questions Search Result</h1>

<table>
<tr>
  <th>Title</th>
  <th>Text</th>
  <th>Author</th>
</tr>

<% @questions.each do |question| %>
  <tr>
    <% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true) %>
    <td><%= link_to question.title, question_path(question) %></td>
    <td>
      <%= markdown.render(question.text).html_safe %>
    </td>
    <td>
      <%= question.user.username %>
    </td>
  </tr>
<% end %>
</table>
<%= paginate @questions %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= form_for :question, url: questions_path do |q| %>
  <p>
    <%= q.label :title %><br>
    <%= q.text_field :title %>
  </p>

  <p>
    <%= q.label :text %><br>
    <%= q.text_area :text %>
  </p>

  <p>
    <%= q.submit %>
  </p>
<% end %>

app/views/questions/searchByTitle.html.erb
<h1>Question Search Results</h1>

app/views/questions/show.html.erb
<h2>
  <strong>Title:</strong>
  <%= @question.title %>
</h2>

<p>
  <% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true) %>
  <%= markdown.render(@question.text).html_safe %>
</p>

<p><%= link_to 'Submit a new Answer', new_question_answer_path(@question) %></p>

<p>
  <strong>Answers:</strong>
  <% @answers.each do |answer| %>
    <% if answer.question_id === @question.id %>
      <h3>Answer by: <%= answer.user.username %></h3>
      <% if answer.correct === true %>
      <p>The question's author has marked this answer as correct.</p>
      <% end %>
      <p><%= answer.text %></p>
      <% if answer.correct === false %>
      <%= link_to 'Mark as Correct', question_answer_path(question_id: answer.question_id, id: answer.id), method: :patch %>
      <% end %>
    <% end %>
  <% end %>
</p>

app/views/questions/welcome.html.erb
<h1>Questions#welcome</h1>
<p>Find me in app/views/questions/welcome.html.erb</p>